
title: Arctic Security
email: contact@arcticsecurity.com
description: Leveling the playing field
baseurl: ""
url: "https://arcticsecurity.com"

timezone: "Europe/Helsinki"
strict_front_matter: true
include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files: [".git", ".svn"]
uploads_dir: "images/content"

markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/
  products:
    output: true
    permalink: /products/:slug/
  news:
    output: true
    permalink: /news/:year/:month/:day/:slug/
  events:
    output: true
    permalink: /events/:year/:month/:day/:slug/
  pages:
    output: true
    permalink: /:path/
  employees:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: blog
  - scope:
      path: "_products"
      type: products
    values:
      layout: product
  - scope:
      path: "_news"
      type: news
    values:
      layout: news-article
  - scope:
      path: "_events"
      type: events
    values:
      layout: event
  
# https://github.com/jekyll/jekyll-sitemap

plugins:
  - jekyll-sitemap

# Misc

_comments:
  show_in_navigation: Is the page displayed in navigation?
  nav_order: Order of the page in navigation
  nav_title: Title shown in navigation
  og_image_path: <br>Displayed when link is shared in social media.
  twitter_image_path: <br>(Optional) Display different image in twitter share.
