
title: Arctic Security
email: contact@arcticsecurity.com
description: Leveling the playing field
baseurl: ""
url: "https://arcticsecurity.com"

timezone: "Europe/Helsinki"
strict_front_matter: true
include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files: [".git", ".svn"]
uploads_dir: "images/content"

markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
collections:
  #products:
  #posts:
  #news:
  #events:
  #partners:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: blog
  
# https://github.com/jekyll/jekyll-sitemap

plugins:
  - jekyll-sitemap

# Misc
homepage_nav_title: Home

_comments:
  show_in_navigation: Is the page displayed in navigation?
  nav_order: Order of the page in navigation
  nav_title: Title shown in navigation
  homepage_nav_title: Title for homepage in navigation
