
title: Arctic Security
email: your-email@example.com
description: Leveling the playing field
#baseurl: "https://arcticsecurity.com"
url: ""

timezone: "Europe/Helsinki"
strict_front_matter: true
include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files: [".git", ".svn"]
uploads_dir: "images/content"

language_shorthand_finnish: "FI"
language_shorthand_english: "EN"

markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
collections:
  #products:
  #posts:
  #news:
  #events:
  #partners:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: blog
  
# https://github.com/jekyll/jekyll-sitemap

plugins:
  - jekyll-sitemap
